#ci.gocd.yaml
format_version: 3
pipelines:
  mypipe1: # definition of mypipe1 pipeline
    group: mygroup # note that the group name can contain only of alphanumeric & underscore characters
    label_template: "${mygit[:8]}"
    lock_behavior: none
    parameters: # list of parameters that can be configured for a pipeline
      param1: value1
    materials:
      mygit: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: https://github.com/naveen-t-2094/gocd-mytest.git
        branch: master

    stages: # list of stages in order
      - build: # name of stage
          clean_workspace: false
          fetch_materials: true
          jobs:
            testJob: # name of the job
              tasks: # ordered list of tasks to execute in job csharp
               - exec: # indicates type of task
                   command: cd
                   arguments: PyTest
               - exec:
                   command: docker build -t test .

              #  - exec: # indicates type of task
                  #  command: docker build
               # shorthand for script-executor plugin
              #  - script: ./build.sh ci